[[main]]
pre = "github"
url = "https://github.com/hrqmonteiro"
identifier = "ZGS1PvvwXN"
weight = 9_999

[[main]]
pre = "linkedin"
url = "https://linkedin.com/hrqmonteiro"
identifier = "H7q040hedU"
weight = 9_999

[[footer]]
none = "none"
